import './globals.css'

export const metadata = {
  title: 'Auco.ai',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='container mx-auto max-w-7xl'>{children}</body>
    </html>
  )
}
